# Generated by Django 4.2.3 on 2023-08-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lesson_4', '0004_alter_advertisement_options_advertisement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='photo',
            field=models.ImageField(default=2, upload_to='photo', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
