# Generated by Django 4.2.3 on 2023-08-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lesson_4', '0011_alter_advertisement_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='photo',
            field=models.ImageField(blank=True, default=6, upload_to='photo', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
