# Generated by Django 4.2.3 on 2023-08-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lesson_4', '0015_alter_advertisement_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='photo',
            field=models.ImageField(blank=True, default='advert/static/img/adv.png', null=True, upload_to='photo', verbose_name='Изображение'),
        ),
    ]
