# Generated by Django 4.2.3 on 2023-08-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lesson_4', '0014_alter_advertisement_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='photo',
            field=models.ImageField(blank=True, default='static/img/images.png', null=True, upload_to='photo', verbose_name='Изображение'),
        ),
    ]
