# Generated by Django 4.2.3 on 2023-08-27 14:38

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_lesson_4', '0019_alter_advertisement_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='titel',
            field=django_ckeditor_5.fields.CKEditor5Field(max_length=50, verbose_name='Заголовок'),
        ),
    ]
