# Generated by Django 4.2.3 on 2023-08-28 20:19

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lesson_4', '0021_alter_advertisement_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='titel',
            field=tinymce.models.HTMLField(verbose_name='Заголовок'),
        ),
    ]
