# Generated by Django 4.2.3 on 2023-08-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lesson_4', '0002_alter_advertisement_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='auction',
            field=models.BooleanField(default=1, help_text='Отметьте, если торг уместен', verbose_name='торг'),
            preserve_default=False,
        ),
    ]
